spring:
  application:
    name:board
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.102:3306/board
    username: arkim
    password: gksmfdlA!01
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html

server:
  port: 8585





